### ISSUE TITLE
support for access to internal representation?

### ISSUE THREAD

**Issue by Paladynee** [cozyGalvinism/break-eternity#3]
Hey. I'm writing the save functionality of my incremental game, and I don't want to use serde to serialize data.

Is it possible to get access to internal representation?
Thanks in advance.

**Comment by Paladynee** [comment]
if marking internal fields pub isnt possible, you can still expose public functions which return them in order to make them read-only.
Rust's Vec currently does this.
```
pub fn len(&self) -> usize {
    self.len
}
```

**Comment by cozyGalvinism** [comment]
Heya! Yeah, I can add that for you!

**Comment by cozyGalvinism** [comment]
Implemented in `cdbc980` and version [`0.2.0`](https://crates.io/crates/break-eternity/0.2.0) (minor version change due to some renaming a typo and some functions to make them more obvious on first sight).
